"""Add voice settings to agents

Revision ID: 62e83b2e245f
Revises:
Create Date: 2026-02-15 22:41:54.466770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "62e83b2e245f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_templates",
        sa.Column("tts_provider", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "agent_templates", sa.Column("voice_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "agent_templates", sa.Column("language", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "agents", sa.Column("tts_provider", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "agents", sa.Column("stt_provider", sa.String(length=50), nullable=True)
    )
    op.alter_column(
        "conversations",
        "conversation_type",
        existing_type=postgresql.ENUM(
            "VOICE_INBOUND",
            "VOICE_OUTBOUND",
            "CHAT",
            "SMS",
            "WHATSAPP",
            "VIDEO",
            name="conversationtype",
        ),
        nullable=True,
    )
    op.alter_column(
        "conversations",
        "transcript",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
        postgresql_using='transcript::json',
    )
    op.alter_column(
        "conversations",
        "duration_seconds",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='duration_seconds::integer',
    )
    op.alter_column(
        "conversations",
        "message_count",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='message_count::integer',
    )
    op.alter_column(
        "conversations",
        "user_message_count",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='user_message_count::integer',
    )
    op.alter_column(
        "conversations",
        "ai_message_count",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='ai_message_count::integer',
    )
    op.alter_column(
        "conversations",
        "user_rating",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='user_rating::integer',
    )
    op.alter_column(
        "conversations",
        "collected_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "call_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column("conversations", "agent_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "conversations", "workspace_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        "conversations_agent_id_fkey", "conversations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "conversations", "agents", ["agent_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "conversations", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "messages",
        "prompt_tokens",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='prompt_tokens::integer',
    )
    op.alter_column(
        "messages",
        "completion_tokens",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='completion_tokens::integer',
    )
    op.alter_column(
        "messages",
        "latency_ms",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using='latency_ms::integer',
    )
    op.alter_column(
        "messages",
        "message_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "message_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "messages",
        "latency_ms",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "messages",
        "completion_tokens",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "messages",
        "prompt_tokens",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.create_foreign_key(
        "conversations_agent_id_fkey",
        "conversations",
        "agents",
        ["agent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "conversations", "workspace_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "conversations", "agent_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "conversations",
        "call_metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "collected_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "user_rating",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=5),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "ai_message_count",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "user_message_count",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "message_count",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "duration_seconds",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "transcript",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        existing_nullable=True,
        postgresql_using='transcript::text',
    )
    op.alter_column(
        "conversations",
        "conversation_type",
        existing_type=postgresql.ENUM(
            "VOICE_INBOUND",
            "VOICE_OUTBOUND",
            "CHAT",
            "SMS",
            "WHATSAPP",
            "VIDEO",
            name="conversationtype",
        ),
        nullable=False,
    )
    op.drop_column("agents", "stt_provider")
    op.drop_column("agents", "tts_provider")
    op.drop_column("agent_templates", "language")
    op.drop_column("agent_templates", "voice_id")
    op.drop_column("agent_templates", "tts_provider")
    # ### end Alembic commands ###